alias ..='cd ..'
alias c='cd'
alias cd..='cd ..'
alias cp='cp -i'
alias df='df -h'
alias du='du -hsc'
alias easy_install='easy_install -d ${PYTHONPATH%:*}'
alias gerp='grep'
alias got='git'
alias grpe='grep'
alias gti='git'
alias hsot='host'
alias l='ls'
alias less='less -S#2'
alias ll='ls -lah'
alias m='more'
alias maek='make'
alias mv='mv -i'
alias noise='printf $(openssl rand 128 -base64 | tr -cd a-hjkp-zACE-HJKP-RT-Z2-4679)\\n'
alias r='R --no-save'
alias rcp='scp -o passwordauthentication=yes -o stricthostkeychecking=no'
alias rsh='ssh -o passwordauthentication=yes -o stricthostkeychecking=no'
