alias ..='cd ..'
alias c='cd'
alias cd..='cd ..'
alias chmdo='chmod'
alias cp='cp -i'
alias cta='cat'
alias df='df -h'
alias du='du -hsc'
alias gerp='grep'
alias gi='git'
alias gitl='git l'
alias got='git'
alias grpe='grep'
alias gti='git'
alias hsot='host'
alias l='ls'
alias lesss='less'
alias ll='ls -lah'
alias m='more'
alias maek='make'
alias mv='mv -i'
alias psa='ps a'
alias qgit='git'
alias r='R --no-save'
alias rot13="tr 'A-Za-z' 'N-ZA-Mn-za-m'"
alias rcp='scp -o passwordauthentication=yes -o stricthostkeychecking=no'
alias rsh='ssh -o passwordauthentication=yes -o stricthostkeychecking=no'
