. ${HOME}/.dotfiles/_environ.sh

export B2_ACCOUNT_INFO="${HOME}/.cache/b2"
export CLASSPATH="${HOME}/Library/Java"
export COPYFILE_DISABLE=true
export COPY_EXTENDED_ATTRIBUTES_DISABLE=true
export GEM_HOME="${HOME}/Library/Ruby"
export GNUPGHOME="${HOME}/work/private/tools/gnupg"
export GOPATH="${HOME}/Library/Go"
export GPG_TTY="$(tty)"
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_GITHUB_API=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export NODENV_ROOT="${HOME}/Library/Node"
export PYTHONPATH="${HOME}/Library/Python"
export R_LIBS_USER="${HOME}/Library/R"
export R_PROFILE_USER="${HOME}/.config/R/profile"
export RBENV_ROOT="${HOME}/Library/Ruby"
